Repository Ox-Chema-xO/Generador-de-manifiestos-de-Kubernetes-parametrizado, pull requests merged in 2025-06, with the labels that each got.

#5 feat: crea templates Deployment, Service y archivo de valores de configuracion values,yaml
  templates/deployment.yaml.template
  templates/example.yaml.template
  templates/service.yaml.template
  templates/values.yaml
Labels: Sprint 1

#7 feat: crea hook pre-commit
  hooks/pre-commit
  requirements.txt
  setup.sh
Labels: Sprint 1

#8 feat: agrega nuevo placeholder protocol
  templates/service.yaml.template
  templates/values.yaml
Labels: Sprint 1

#15 refactor: mejora la generacion de manifiestos para multiples manifiestos
  src/manifest_generator.py
  tests/test_multiples_manifiestos.py
Labels: Sprint 2

#19 release: integrar cambios del Sprint 2
  README.md
  requirements.txt
  src/manifest_generator.py
  tests/test_multiples_manifiestos.py
  tests/test_validacion.py
  tests/test_validar_values.py
Labels: Sprint 2

#20 feat: desplegar manifiestos en un cluster de kubernetes local
  src/manifest_generator.py
Labels: Sprint 3

#21 feat: se compara el enfoque de nuestro generador con Helm Charts
  comparar.sh
  helm-chart/app-chart/.helmignore
  helm-chart/app-chart/Chart.yaml
  helm-chart/app-chart/templates/_helpers.tpl
  helm-chart/app-chart/templates/deployment.yaml
  helm-chart/app-chart/templates/service.yaml
  helm-chart/app-chart/values.yaml
Labels: Sprint 3

#23 release: agrega los cambios realizados en el Sprint 3
  README.md
  comparar.sh
  helm-chart/app-chart/.helmignore
  helm-chart/app-chart/Chart.yaml
  helm-chart/app-chart/templates/_helpers.tpl
  helm-chart/app-chart/templates/deployment.yaml
  helm-chart/app-chart/templates/service.yaml
  helm-chart/app-chart/values.yaml
  requirements.txt
  src/manifest_generator.py
  tests/test_e2e_local.py
Labels: Sprint 3
